### ISSUE TITLE
URL to manually download the databases?

### ISSUE THREAD

**Issue by ruizhao087** [cmkobel/CompareM2#107]
Hi CompareM2 developers, 
Thanks for the efforts to make comparative genomic analysis easier! I am getting it installed to give it a try.
I wonder whether it is possible to post the URL of the databases? I easily exceeded the quota limit of my account on our HPC when downloading the databases using "comparem2 --until downloads", given that they are 200 GB. I hope to store them somewhere else rather than the default Miniforge directory within my home directory. Thank you in advance!

Rui

**Comment by cmkobel** [comment]
Hi

Yes, you can use -p to show the command, and --dry-run to not run it but just show what will run:

`comparem2 --until downloads --dry-run -p`

This will give you the full scripts that are run under the hood and you can copy-paste that and run it manually if you wish.

Good luck.

**Comment by ruizhao087** [comment]
Hi Carl,
Thank you for the help! It worked. I downloaded the databases and can finish the testing runs. Awesome and comprehensive tool!

Rui
