### ISSUE TITLE
Eggnog fails if version installed is above or equal to 2.1.7

### ISSUE THREAD

**Issue by michoug** [cmkobel/CompareM2#108]
Hi
The eggnog rule fails if eggnog mapper is above or equal to 2.1.7 because it creates a gff file ending with `.emapper.genepred.gff` instead of `.emapper.gff` as is the case now

https://github.com/eggnogdb/eggnog-mapper/wiki/eggNOG-mapper-v2.1.5-to-v2.1.12#v217

`Changes in GFF decoration to (hopefully) fix issue #367 , in which positions were relative to the ORF (1-end) instead of relative to the contig which contains the ORF. Now, 2 GFF files will be created when using gene prediction and gff decoration: one ".genepred.gff" from either Prodigal or blastx-like hits, one ".decorated.gff" with the annotations added as attributes.`

May I suggest to specify the versions of the tools in the `env` files to avoid such issues.
Cheers
Greg

**Comment by cmkobel** [comment]
Hi Greg

Thanks for pointing this out. 

I'm now pinning v2.1.12, and setting the expected output to expect .emapper.decorated.gff and .emapper.genepred.gff

Best

**Comment by cmkobel** [comment]
Fix is out https://github.com/bioconda/bioconda-recipes/pull/49572
