### ISSUE TITLE
Insatlling comparem2

### ISSUE THREAD

**Issue by bharat1912** [cmkobel/CompareM2#111]
1. Installed comparem2 - mamba create -c conda-forge -c bioconda -n comparem2 comparem2
2. conda activate comparem2
3. Ran test from E._faecium dir which contains 3 genome sequences- $comparem2
4. Error- 
Using profile /pvol/opt/mambaforge/envs/comparem2/share/comparem2-2.11.1-0/profile/conda/default for setting default command line arguments.
                   Formerly known as Assemblycomparator2              
                       github.com/cmkobel/comparem2/issues               
                             comparem2.readthedocs.io                    
                                     v2.11.1
                                                                         
  Variables                                                              
  ---------                                                              
    title         : 'E._faecium'
    base          : '/pvol/opt/mambaforge/envs/comparem2/share/comparem2-2.11.1-0'
    databases     : '/pvol/opt/mambaforge/envs/comparem2/share/comparem2-2.11.1-0/databases'
                                                                         
  Available rules                                                        
  ---------------                                                        
    Q.C.          : copy assembly_stats sequence_lengths checkm2 busco   
    Annotate      : prokka bakta                                         
    Adv. annotate : eggnog interproscan dbcan kegg_pathway abricate mlst 
    Core-pan      : panaroo                                              
    Phylogenetic  : mashtree fasttree gtdbtk iqtree treecluster snp_dists
    Pseudo        : meta isolate downloads fast report                   
  (Use ´--until <rule> [<rule2>..]´ to activate only one or more rules)  

  Sample overview
  ---------------
 1-index input_file sample
       1  116_2.fna  116_2
       2  E8202.fna  E8202
       3  SRR24.fna  SRR24
//

Building DAG of jobs...
Creating conda environment /pvol/opt/mambaforge/envs/comparem2/share/comparem2-2.11.1-0/workflow/rules/../envs/busco.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /pvol/opt/mambaforge/envs/comparem2/share/comparem2-2.11.1-0/workflow/rules/../envs/busco.yaml:
Command:
mamba env create --quiet --file "/home/ubuntu/.comparem2/conda/f295c6980d643e54c7ab7677357928f0_.yaml" --prefix "/home/ubuntu/.comparem2/conda/f295c6980d643e54c7ab7677357928f0_"
Output:
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.

**Comment by cmkobel** [comment]
What version of conda are you running? Could you try updating with `conda update conda`, and try again? You might have to reset your ~/.comparem2 directory with `rm -rf ~/.comparem2`.

**Comment by bharat1912** [comment]
Thanks for rapid respone. Much appreciated.

I have installed the dockker version of comparem2-2.11.1-0 as I had a problem with my primary disk  running out of space. I have created a docker env with mamba, installed docker and pulled comparem2 image, moved /var/lib/docker  to another location which had more disk space. I am testing it out at the moment. 

I will close this issue but will keep you informed. 

Thanks again

**Comment by bharat1912** [comment]
1. I am reopening the error in busco. This is the error in busco, though checkm2 works so this is not an issue but I am reporting it.    ---------------------------------------------------
    |Results from generic domain bacteria_odb10        |
    ---------------------------------------------------
    |C:99.2%[S:99.2%,D:0.0%],F:0.8%,M:0.0%,n:124       |
    |123    Complete BUSCOs (C)                        |
    |123    Complete and single-copy BUSCOs (S)        |
    |0    Complete and duplicated BUSCOs (D)           |
    |1    Fragmented BUSCOs (F)                        |
    |0    Missing BUSCOs (M)                           |
    |124    Total BUSCO groups searched                |
    ---------------------------------------------------

    ---------------------------------------------------
    |Results from dataset mycoplasmatales_odb10        |
    ---------------------------------------------------
    |C:92.0%[S:91.4%,D:0.6%],F:1.7%,M:6.3%,n:174       |
    |160    Complete BUSCOs (C)                        |
    |159    Complete and single-copy BUSCOs (S)        |
    |1    Complete and duplicated BUSCOs (D)           |
    |3    Fragmented BUSCOs (F)                        |
    |11    Missing BUSCOs (M)                          |
    |174    Total BUSCO groups searched                |
    ---------------------------------------------------
2024-10-19 11:54:52 INFO:	BUSCO analysis done. Total running time: 76 seconds
2024-10-19 11:54:52 INFO:	Results written in pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco
2024-10-19 11:54:52 INFO:	For assistance with interpreting the results, please consult the userguide: https://busco.ezlab.org/busco_userguide.html

2024-10-19 11:54:52 INFO:	Visit this page https://gitlab.com/ezlab/busco#how-to-cite-busco to see how to cite BUSCO
2024-10-19 11:54:52 INFO:	[hmmsearch]	100 of 124 task(s) completed
[11:54:52] Excluding CDS which overlaps existing RNA (tRNA) at gnl|Prokka|NCKHFOEE_12:372289..372441 on - strand
2024-10-19 11:54:52 INFO:	[hmmsearch]	112 of 124 task(s) completed
[11:54:53] Excluding CDS which overlaps existing RNA (rRNA) at gnl|Prokka|NCKHFOEE_57:276..740 on - strand
2024-10-19 11:54:53 INFO:	[hmmsearch]	112 of 124 task(s) completed
[11:54:53] Found 2741 CDS
[11:54:53] Connecting features back to sequences
[11:54:53] Not using genus-specific database. Try --usegenus to enable it.
[11:54:53] Annotating CDS, please be patient.
[11:54:53] Will use 4 CPUs for similarity searching.
cat: '/pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco/auto_lineage/*/short_summary.json': No such file or directory
[Sat Oct 19 11:54:53 2024]
Error in rule busco:
    jobid: 49
    output: /pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco/busco_done.flag, /pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco/short_summary_extract.tsv
    conda-env: /pvol/conda_envs/07df8e5f1335cbb72312ae9ac6e9feb1_
    shell:
        

        # Collect version number.
        busco -v > "$(dirname /pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco/short_summary_extract.tsv)/.software_version.txt"
        
        # Collect database version.
        echo -e "$(date -Iseconds)	/pvol/databases/comparem2_db/busco/comparem2_busco_database_representative.flag" > "$(dirname /pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco/short_summary_extract.tsv)/.database_version.txt"

        # Busco fails because of a problem with the sepp package. This doesn't really matter as we just want the completeness results.
        # But, this means that we need a hacky workaround to let this job exit gracefully (exit code 0) on the basis of whether any completeness results have been written to disk.
        # Hence, the actual exit code of busco, we will ignore.        
        
        # https://busco.ezlab.org/busco_userguide.html#offline
        # Is the timeout bug fixed? Update: nope.
        timeout 1800             busco                 --cpu 1                 --in /pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/prokka/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641.faa                 --out /pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco                 --force                 --skip_bbtools                 --download_path /pvol/databases/comparem2_db/busco                 --mode protein                 --tar --auto-lineage-prok                 --offline || (>&2 echo "comparem2: Busco failed internally.")

        # Cat all auto lineage results together or create empty file
        # The following cat command will fail if the glob doesn't resolve any files: This is the wanted behaviour.
        cat /pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco/auto_lineage/*/short_summary.json         > "/pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco/short_summary_extract.tsv_temp"
        
        >&2 echo "comparem2: Intermediate results have been collected, as they are still useful."
        
        # Extract relevant features
        cat "/pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco/short_summary_extract.tsv_temp"         | grep -oE "(\"in\"|\"name\"|\"one_line_summary\").+"         > /pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco/short_summary_extract.tsv

        # Clean up
        rm "/pvol/Anoxy_comparem2/Anoxy_comparem2_results/samples/GCA_002243705_1_Anoxybacillus_flavithermus_DSM2641/busco/short_summary_extract.tsv_temp" || echo "no file"
        
        mv busco_*.log .snakemake/log || echo "no logs to move"
        date -Iseconds >> /pvol/Anoxy_comparem2/Anoxy_comparem2_results/.comparem2_void_report.flag
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

2. I am running: comparem2 v2.11.1 installed with mamba (miniforge2): mamba 1.5.10 and conda 24.9.1 
3. Conda list: 
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
amply                     0.1.6              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
boltons                   24.0.0             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py310hf71b8c6_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.32.3               h4bc722e_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py310h8deb56e_0    conda-forge
charset-normalizer        3.4.0              pyhd8ed1ab_0    conda-forge
coin-or-cbc               2.10.12              h8b142ea_1    conda-forge
coin-or-cgl               0.60.9               h1d3f3f2_0    conda-forge
coin-or-clp               1.17.10              h07f2a63_0    conda-forge
coin-or-osi               0.108.11             h6514dde_1    conda-forge
coin-or-utils             2.11.12              h99da652_1    conda-forge
coincbc                   2.10.12           1_metapackage    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comparem2                 2.11.1               hdfd78af_0    bioconda
conda                     24.9.1          py310hff52083_0    conda-forge
conda-libmamba-solver     24.9.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.3.0              pyh7900ff3_0    conda-forge
conda-package-streaming   0.10.0             pyhd8ed1ab_0    conda-forge
configargparse            1.7                pyhd8ed1ab_0    conda-forge
connection_pool           0.0.3              pyhd3deb0d_0    conda-forge
cpp-expected              1.1.0                hf52228f_0    conda-forge
datrie                    0.8.2           py310ha75aee5_8    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
docutils                  0.21.2             pyhd8ed1ab_0    conda-forge
dpath                     2.2.0              pyha770c72_0    conda-forge
filelock                  3.16.1             pyhd8ed1ab_0    conda-forge
fmt                       11.0.2               h434a139_0    conda-forge
frozendict                2.4.5           py310ha75aee5_0    conda-forge
gitdb                     4.0.11             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.43             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.10               pyhd8ed1ab_0    conda-forge
importlib_resources       6.4.5              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py310hff52083_1    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2024.10.1          pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2              pyh31011fe_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_1    conda-forge
libarchive                3.7.4                hfca40fe_0    conda-forge
libblas                   3.9.0           24_linux64_openblas    conda-forge
libcblas                  3.9.0           24_linux64_openblas    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgfortran               14.1.0               h69a702a_1    conda-forge
libgfortran-ng            14.1.0               h69a702a_1    conda-forge
libgfortran5              14.1.0               hc5f4f2c_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0           24_linux64_openblas    conda-forge
liblapacke                3.9.0           24_linux64_openblas    conda-forge
libmamba                  1.5.10               hf72d635_1    conda-forge
libmambapy                1.5.10          py310h6639945_1    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libsolv                   0.7.30               h3509ff9_0    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
mamba                     1.5.10          py310h51d5547_1    conda-forge
markupsafe                3.0.1           py310h89163eb_1    conda-forge
menuinst                  2.1.2           py310hff52083_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
nlohmann_json             3.11.3               he02047a_1    conda-forge
numpy                     2.1.2           py310hd6e36ab_0    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.3           py310h5eaa309_1    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
plac                      1.4.3              pyhd8ed1ab_0    conda-forge
platformdirs              4.3.6              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
psutil                    6.0.0           py310ha75aee5_1    conda-forge
pulp                      2.7.0           py310hff52083_1    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py310h2372a71_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.4              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.0          h543edf9_3_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-tzdata             2024.2             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    5_cp310    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py310ha75aee5_1    conda-forge
ratelimiter               1.2.0           pyhd8ed1ab_1003    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
reproc                    14.2.4.post0         hd590300_1    conda-forge
reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
reretry                   0.11.8             pyhd8ed1ab_0    conda-forge
rpds-py                   0.20.0          py310h505e2c1_1    conda-forge
ruamel.yaml               0.18.6          py310h2372a71_0    conda-forge
ruamel.yaml.clib          0.2.8           py310h2372a71_0    conda-forge
scipy                     1.14.1          py310ha3fb0e1_0    conda-forge
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
simdjson                  3.10.1               h84d6215_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smart_open                7.0.5              pyhd8ed1ab_1    conda-forge
smmap                     5.0.0              pyhd8ed1ab_0    conda-forge
snakemake-minimal         7.15.2             pyhdfd78af_0    bioconda
spdlog                    1.14.1               hed91bc2_1    conda-forge
sqlite                    3.46.1               h9eae976_0    conda-forge
stopit                    1.1.2                      py_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
toposort                  1.10               pyhd8ed1ab_0    conda-forge
tqdm                      4.66.5             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
truststore                0.9.2              pyhd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
urllib3                   2.2.3              pyhd8ed1ab_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0          py310ha75aee5_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
yte                       1.5.4              pyha770c72_0    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
zstandard                 0.23.0          py310ha39cb0e_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

4. I have run metagenomes (bins from metawrap) and the following are reported from in the report section (anismash is missing): 
assembly_stats | 1 / 1 | 🟢 yes
sequence_lengths | 88 / 88 | 🟢 yes
busco | 0 / 88 | 🟠 no
checkm2 | 1 / 1 | 🟢 yes
gtdbtk | 1 / 1 | 🟢 yes
mlst | 1 / 1 | 🟢 yes
abricate | 4 / 4 | 🟢 yes
prokka | 88 / 88 | 🟢 yes
kegg_pathway | 0 / 1 | 🟠 no
dbcan | 88 / 88 | 🟢 yes
panaroo | 1 / 1 | 🟢 yes
snp_dists | 0 / 1 | 🟠 no
mashtree | 1 / 1 | 🟢 yes
Thanks
